In [1]:
# import csv
import pandas as pd
df=pd.DataFrame(columns=["Tweet_index","Label","Tweet_Text"]);
txt_file=r"SemEval2018-T3-train-taskB_emoji_ironyHashtags.txt"
#csv_file=r"data11.csv"
i=0
with open(txt_file) as f:
    for line in f:
        #print(line)
        if i==0:
            i=i+1
            continue
        #print(line)
        df.loc[i]=[text for text in line.split("\t")]
        i=i+1

#df=pd.read_csv('input_data_TrainA.csv',sep='\t')
#print(df)
tweets=df["Tweet_Text"]
label=df["Label"]
print(len(tweets))

3834


In [2]:
import csv
import pandas as pd
import numpy as np
import re
X=[]
Y=[]
X1=[]
X2=[]
Y1=[]
regex = re.compile(r'[\t]')
with open('outfiles/merged_input_file_TrainB.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader)
    for row in reader:
        row[0]=row[0].replace('"',"")
        row[0]=regex.sub(" ",row[0])
        li = list(row[0].split(" "))
        li = [i for i in li if len(i) >= 1]
        li = list(map(float, li))     
        X.append(li)
y=label
print(X[:2])
#X1=sum(X, [])
print(len(y))
print(len(X))
#print(X)

for i in range(3834):
    Y.append((list(y.iloc[i])))
    
Y2=[]
for i in range(3834):
    y2=[]
    for x in Y[i]:
        y2.append(float(x))
        Y2.append(y2)
print(Y2[:5])
#print(X2[:5])
#print(Y[:5])
y1=np.array(Y2)
x1=np.array(X)


[[1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 4.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.030612244897959183, 3.0, 1.0, 0.0, 0.0, 0.0, 3.0, 0.23, 1.0, 0.0, 98.0], [2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 0.0, 1.0, 1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 2.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 3.0, 4.0, 1.0, 0.0, 1.0, 1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 2.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.030303030303030304, 4.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.05, 1.0, 0.0, 132.0]]
3834
3834
[[1.0], [1.0], [1.0], [0.0], [2.0]]


In [3]:
predict_TestB=[]
with open('outfiles/merged_input_file_TestB.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader)
    for row in reader:
        row[0]=regex.sub(" ",row[0])
        li = list(row[0].split(" "))
        li = [i for i in li if len(i) >= 1]
        li = list(map(float, li))
        predict_TestB.append(li)

In [34]:
import keras
from keras.optimizers import SGD , Adam
from keras.models import Sequential
from keras.layers import Dense
def buildmodel():
    print("Now we build the model")
    model = Sequential()
    model.add(Dense(60, activation='relu', input_dim=90))
    model.add(Dense(1, activation='softmax'))
    sgd = SGD(lr=0.0001)# decay=1e-6, momentum=0.9, nesterov=True)
    model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])
    print("We finish building the model")
    return model

model = buildmodel()
model.fit(x1,y1, epochs=41, batch_size=64)


Now we build the model
We finish building the model
Epoch 1/41
3834/3834 [==============================] - 1s 169us/step - loss: 4.9773 - acc: 0.3625
Epoch 2/41
3834/3834 [==============================] - 0s 25us/step - loss: 4.9773 - acc: 0.3625
Epoch 3/41
3834/3834 [==============================] - 0s 25us/step - loss: 4.9773 - acc: 0.3625
Epoch 4/41
3834/3834 [==============================] - 0s 22us/step - loss: 4.9773 - acc: 0.3625
Epoch 5/41
3834/3834 [==============================] - 0s 23us/step - loss: 4.9773 - acc: 0.3625
Epoch 6/41
3834/3834 [==============================] - 0s 22us/step - loss: 4.9773 - acc: 0.3625
Epoch 7/41
3834/3834 [==============================] - 0s 25us/step - loss: 4.9773 - acc: 0.3625
Epoch 8/41
3834/3834 [==============================] - 0s 28us/step - loss: 4.9773 - acc: 0.3625
Epoch 9/41
3834/3834 [==============================] - 0s 24us/step - loss: 4.9773 - acc: 0.3625
Epoch 10/41
3834/3834 [==============================] - 0s 29us/

In [35]:

model.predict(np.array(list(x1)))[:200]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [6]:
#!pip install tensorflow

In [7]:
#!pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

In [8]:
#conda install tensorflow

In [9]:
print(x1)

[[1.000e+00 0.000e+00 2.000e+00 ... 1.000e+00 0.000e+00 9.800e+01]
 [2.000e+00 1.000e+00 0.000e+00 ... 1.000e+00 0.000e+00 1.320e+02]
 [3.000e+00 0.000e+00 0.000e+00 ... 1.000e+00 0.000e+00 5.900e+01]
 ...
 [3.832e+03 0.000e+00 1.000e+00 ... 1.000e+00 0.000e+00 1.020e+02]
 [3.833e+03 0.000e+00 0.000e+00 ... 1.000e+00 0.000e+00 1.320e+02]
 [3.834e+03 1.000e+00 1.000e+00 ... 1.000e+00 0.000e+00 1.060e+02]]


In [10]:
print(x1[0])

[1.00000000e+00 0.00000000e+00 2.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 2.00000000e+00 2.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 2.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 4.00000000e+00 5.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.000000